combine_vue_and_django/api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path("todo/list/", views.ApiTodoLV.as_view(), name="list"),
    path("todo/<int:pk>/delete/", views.ApiTodoDelV.as_view(), name="delete"),
    path("todo/create/", views.ApiTodoCV.as_view(), name="create"),
]

combine_vue_and_django/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.HomeView.as_view(), name="home"),
    path("todo/", include("todo.urls")),
    path("api/", include("api.urls")),
]

combine_vue_and_django/todo/urls.py
from django.urls import path
from . import views

app_name = "todo"

urlpatterns = [
    path("", views.TodoTV.as_view(), name="index"),
]

combine_vue_and_django/api/models.py
from django.db import models

# Create your models here.

combine_vue_and_django/todo/models.py
from collections.abc import Iterable
from django.db import models

# Create your models here.


class Todo(models.Model):
    name = models.CharField("NAME", max_length=5, blank=True)
    todo = models.CharField("TODO", max_length=50, blank=False)

    def __str__(self):
        return self.todo

    def save(
        self,
        force_insert: bool = False,
        force_update: bool = False,
        using: str | None = None,
        update_fields: Iterable[str] | None = None,
    ):
        if not self.name:
            self.name = "abc"

        super().save(force_insert, force_update, using, update_fields)

combine_vue_and_django/api/views.py
import json
from django.forms import model_to_dict
from django.http import JsonResponse
from django.views.generic.edit import BaseDeleteView, BaseCreateView
from django.views.generic.list import BaseListView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import ensure_csrf_cookie

from todo.models import Todo


# Create your views here.
@method_decorator(ensure_csrf_cookie, name="dispatch")
class ApiTodoLV(BaseListView):
    model = Todo

    def render_to_response(self, context, **response_kwargs):
        todoList = list(context["object_list"].values())

        return JsonResponse(data=todoList, safe=False)


class ApiTodoDelV(BaseDeleteView):
    model = Todo

    def delete(self, request, *args, **kwarg):
        self.object = self.get_object()
        self.object.delete()
        return JsonResponse(data={}, status=204)


class ApiTodoCV(BaseCreateView):
    model = Todo
    fields = "__all__"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["data"] = json.loads(self.request.body)

        return kwargs

    def form_valid(self, form):
        self.object = form.save()

        newTodo = model_to_dict(self.object)

        return JsonResponse(data=newTodo, status=201)

    def form_invalid(self, form):
        return JsonResponse(data=form.errors, status=400)

combine_vue_and_django/mysite/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home.html"

combine_vue_and_django/todo/views.py
from django.views.generic import TemplateView


# Create your views here.
class TodoTV(TemplateView):
    template_name = "todo/todo_index.html"

combine_vue_and_django/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <title>{% block title %}home.html{% endblock %}</title>

        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
            integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" />
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />

        {% block extra-style %}{% endblock %}
    </head>

    <body style="padding-top: 90px">
        <!-- Main Menu -->
        <nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">
            <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Vue-Django System</span>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'todo:index' %}">Todo</a>
                    </li>
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'home' %}">Blog(to be)</a>
                    </li>

                    <li class="nav-item dropdown mx-1 btn btn-primary">
                        <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">Util</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                            <div class="dropdown-divider"></div>
                        </div>
                    </li>
                </ul>

                <form class="form-inline my-2">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" />
                </form>

                <ul class="navbar-nav ml-5 mr-5">
                    <li class="nav-item dropdown mx-1 btn btn-primary">
                        <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">
                            <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;</a
                        >
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'home' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'home' %}">Register</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container">{% block content %}{% endblock %}</div>

        {% block footer %}{% endblock %}

        <!-- Bootstrap core JavaScript -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>

        {% block extra-script %}{% endblock %}
    </body>
</html>

combine_vue_and_django/templates/home.html
{% extends 'base.html' %} {% load static %} {% block title %}home.html{% endblock %} {% block extra-style %}
<style>
    .home-window {
        background-image: url('{% static 'img/lion.jpg' %}');
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100%;
        height: 500px;
        border-top: 10px solid #ccc;
        border-bottom: 10px solid #ccc;
        color: yellow;
        padding: 20px 0 0 20px;
    }
    .title {
        color: #c80;
        font-weight: bold;
    }
    .powered {
        position: relative;
        top: 77%;
        color: #cc0;
        font-style: italic;
    }
</style>
{% endblock %} {% block content %}
<div class="home-window">
    <h2 class="title">Django - Python Web Programming</h2>
    <h4 class="powered"><i class="fas fa-cog"></i> powered by django and bootstrap.</h4>
</div>

<hr style="margin: 10px 0" />

<div class="row text-center">
    <div class="col-sm-6">
        <h4 class="fw-bold">Todo App</h4>
        <p>
            With Todo app, you can manage, prioritize, and complete the most important things you need to do every day. I can focus on the most important things
            and I can do my day more deliberately. You can also share lists with colleagues, friends, and family.
        </p>
    </div>
    <div class="col-sm-6">
        <h4 class="fw-bold">Blog App</h4>
        <p>
            This application makes it possible to log daily events or write your own interests such as hobbies, techniques, etc. A typical blog combines text,
            digital images, and links to other blogs, web pages, and other media related to its topic.
        </p>
    </div>
</div>
{% endblock content %} {% block footer %}
<footer class="fixed-bottom">
    <div class="container-fluid">
        <div class="row ttext-center bg-light p-3 d-flex justify-content-between">
            <div class="col-md-6 fw-bold">
                <p>Copyright &copy; 2023 Vue-Django by Yuheon Kim</p>
            </div>
            <div class="col-md-6">
                <ul class="list-inline d-flex justify-content-end fw-bold">
                    <li class="me-3" data-bs-toggle="tooltip" data-bs-placement="top" title="준비중입니다">About</li>
                    <li class="me-3" data-bs-toggle="tooltip" data-bs-placement="top" title="준비중입니다">Help</li>
                    <li class="me-3" data-bs-toggle="tooltip" data-bs-placement="top" title="준비중입니다">Policy</li>
                    <li class="me-0" data-bs-toggle="tooltip" data-bs-placement="top" title="준비중입니다">Something</li>
                </ul>
            </div>
        </div>
    </div>
</footer>
{% endblock footer %} {% block extra-script %}
<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl);
    });
</script>
{% endblock extra-script %}

combine_vue_and_django/templates/todo/todo_index.html
{% extends "base.html" %} {% block title %}todo_index.html{% endblock title %} {% block extra-style %}

<style>
    body {
        text-align: center;
        background-color: #ddd;
    }
    .inputBox {
        margin: auto;
        width: 70%;
        background: white;
        height: 50px;
        border-radius: 50px;
        line-height: 50px;
    }
    .inputBox .name {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 90px;
        padding-left: 20px;
        line-height: 20px;
    }
    .inputBox .item {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 400px;
        margin-left: 50px;
        padding-left: 20px;
        line-height: 20px;
    }
    .todoList {
        list-style: none;
        padding: 10px 0;
        text-align: left;
    }
    .todoList li {
        display: flex;
        height: 50px;
        line-height: 50px;
        margin: 0.5rem 0;
        padding: 0 0.9rem;
        background: white;
        border-radius: 5px;
    }
    .removeBtn {
        margin-left: auto;
        font-size: 20px;
        cursor: pointer;
    }
    .removeBtn:hover {
        color: red;
    }
</style>
{% endblock extra-style %} {% block content %}

<div id="app">
    <h1>My To Do App !</h1>
    <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
    <br />

    <div class="inputBox">
        <input v-model.trim="name" class="name" type="text" placeholder="name ..." />
        <input v-model.trim="todo" class="item" type="text" placeholder="type anything welcomed ..." v-on:keyup.enter="addTodo()" />
        <button v-on:click="addTodo()" class="btn btn-primary btn-sm">ADD</button>
    </div>

    <ul class="todoList">
        <li v-for="(todo, index) in todoList">
            <span>[[ todo.name ]]: [[ todo.todo ]] </span>
            <span class="removeBtn" v-on:click="removeTodo(todo, index)">&#x00D7;</span>
        </li>
    </ul>
</div>
{% endblock content %} {% block extra-script %}
<script src="https://unpkg.com/vue@2"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.xsrfHeaderName = 'X-CSRFToken';

    var vm = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
            name: '',
            todo: '',
            todoList: [],
        },
        created: function () {
            console.log('created');
            this.fetch_all_todo();
        },
        methods: {
            addTodo: function () {
                console.log('add');
                if (!this.name) this.name = 'abc';
                if (!this.todo) {
                    this.name = '';
                    return;
                }

                var vm = this;
                var postData = { name: this.name, todo: this.todo };
                axios
                    .post('/api/todo/create/', postData)
                    .then(function (res) {
                        console.log('POST RES', res);
                        vm.todoList.push({ id: res.data.id, name: res.data.name, todo: res.data.todo });
                    })
                    .catch(function (err) {
                        console.log('POST ERR', err);
                        alert(err.response.status + ' ' + err.response.statusText);
                    });
                this.name = this.todo = '';
            },
            removeTodo: function (todo, index) {
                console.log('remove');
                if (confirm('Really delete ?') == false) return;

                const vm = this;
                axios
                    .delete('/api/todo/' + todo.id + '/delete/')
                    .then(function (res) {
                        console.log('remove res', res);
                        vm.todoList.splice(index, 1);
                    })
                    .catch(function (e) {
                        console.log('error', e);
                    });
            },
            fetch_all_todo: function () {
                console.log('fetch_all_todo');
                const vm = this;
                axios
                    .get('/api/todo/list/')
                    .then(function (res) {
                        console.log('GET RES', res);
                        vm.todoList = res.data;
                    })
                    .catch(function (e) {
                        console.log('error', e);
                    });
            },
        },
    });
</script>
{% endblock extra-script %}