only_used_one_of_vue_and_django/Django/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("todo/", include("to_do.urls")),
]

only_used_one_of_vue_and_django/Django/to_do/urls.py
from . import views
from django.urls import path

app_name = "todo"

urlpatterns = [
    path("vonly/", views.ToDoVueOnlyTV.as_view(), name="vonly"),
    path("create/", views.ToDoCV.as_view(), name="create"),
    path("list/", views.ToDoLV.as_view(), name="list"),
    path("<int:pk>/delete/", views.ToDoDelV.as_view(), name="delete"),
    path("mixin/", views.ToDoMOMCV.as_view(), name="mixin"),
    path("<int:pk>/delete2/", views.ToDoDelV2.as_view(), name="delete2"),
]

only_used_one_of_vue_and_django/Django/to_do/models.py
from collections.abc import Iterable
from django.db import models

# Create your models here.


class Todo(models.Model):
    name = models.CharField("NAME", max_length=5, blank=True)
    todo = models.CharField("TODO", max_length=50, blank=False)

    def __str__(self):
        return self.todo

    def save(
        self,
        force_insert: bool = False,
        force_update: bool = False,
        using: str | None = None,
        update_fields: Iterable[str] | None = None,
    ) -> None:
        if not self.name:
            self.name = "abc"

        return super().save(force_insert, force_update, using, update_fields)

only_used_one_of_vue_and_django/Django/to_do/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from to_do.models import Todo

# Create your views here.


class ToDoVueOnlyTV(TemplateView):
    template_name = "todo/todo_vue_only.html"


class ToDoCV(CreateView):
    model = Todo
    fields = "__all__"
    template_name = "todo/todo_form.html"
    success_url = reverse_lazy("todo:list")


class ToDoLV(ListView):
    model = Todo
    template_name = "todo/todo_list.html"


class ToDoDelV(DeleteView):
    model = Todo
    template_name = "todo/todo_confirm_delete.html"
    success_url = reverse_lazy("todo:list")


class ToDoMOMCV(MultipleObjectMixin, CreateView):
    model = Todo
    fields = "__all__"
    template_name = "todo/todo_form_list.html"
    success_url = reverse_lazy("todo:mixin")

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super().post(request, *args, **kwargs)


class ToDoDelV2(DeleteView):
    model = Todo
    success_url = reverse_lazy("todo:mixin")

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

only_used_one_of_vue_and_django/Django/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <title>{% block title %}home.html{% endblock %}</title>

        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
            integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" />
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />

        {% block extra-style %}{% endblock %}
    </head>

    <body style="padding-top: 90px">
        <!-- Main Menu -->
        <nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">
            <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Vue-Django System</span>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'todo:vonly' %}">VueOnly</a>
                    </li>
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'todo:create' %}">DjangoOnly</a>
                    </li>
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'todo:mixin' %}">DjangoMixin</a>
                    </li>

                    <li class="nav-item dropdown mx-1 btn btn-primary">
                        <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">Util</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                            <div class="dropdown-divider"></div>
                        </div>
                    </li>
                </ul>

                <form class="form-inline my-2">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" />
                </form>

                <ul class="navbar-nav ml-5 mr-5">
                    <li class="nav-item dropdown mx-1 btn btn-primary">
                        <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">
                            <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;</a
                        >
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'home' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'home' %}">Register</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container">{% block content %}{% endblock %}</div>

        {% block footer %}{% endblock %}

        <!-- Bootstrap core JavaScript -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>

        {% block extra-script %}{% endblock %}
    </body>
</html>