only_used_one_of_vue_and_django/Django/to_do/urls.py
from . import views
from django.urls import path

app_name = "todo"

urlpatterns = [
    path("vonly/", views.ToDoVueOnlyTV.as_view(), name="vonly"),
    path("create/", views.ToDoCV.as_view(), name="create"),
    path("list/", views.ToDoLV.as_view(), name="list"),
    path("<int:pk>/delete/", views.ToDoDelV.as_view(), name="delete"),
    path("mixin/", views.ToDoMOMCV.as_view(), name="mixin"),
    path("<int:pk>/delete2/", views.ToDoDelV2.as_view(), name="delete2"),
]

only_used_one_of_vue_and_django/Django/to_do/models.py
from collections.abc import Iterable
from django.db import models

# Create your models here.


class Todo(models.Model):
    name = models.CharField("NAME", max_length=5, blank=True)
    todo = models.CharField("TODO", max_length=50, blank=False)

    def __str__(self):
        return self.todo

    def save(
        self,
        force_insert: bool = False,
        force_update: bool = False,
        using: str | None = None,
        update_fields: Iterable[str] | None = None,
    ) -> None:
        if not self.name:
            self.name = "abc"

        return super().save(force_insert, force_update, using, update_fields)

only_used_one_of_vue_and_django/Django/to_do/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from to_do.models import Todo

# Create your views here.


class ToDoVueOnlyTV(TemplateView):
    template_name = "todo/todo_vue_only.html"


class ToDoCV(CreateView):
    model = Todo
    fields = "__all__"
    template_name = "todo/todo_form.html"
    success_url = reverse_lazy("todo:list")


class ToDoLV(ListView):
    model = Todo
    template_name = "todo/todo_list.html"


class ToDoDelV(DeleteView):
    model = Todo
    template_name = "todo/todo_confirm_delete.html"
    success_url = reverse_lazy("todo:list")


class ToDoMOMCV(MultipleObjectMixin, CreateView):
    model = Todo
    fields = "__all__"
    template_name = "todo/todo_form_list.html"
    success_url = reverse_lazy("todo:mixin")

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super().post(request, *args, **kwargs)


class ToDoDelV2(DeleteView):
    model = Todo
    success_url = reverse_lazy("todo:mixin")

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

only_used_one_of_vue_and_django/Django/to_do/templates/todo/todo_confirm_delete.html
{% extends "base.html" %} {% block title %}todo_confirm_delete.html{% endblock title %} {% block extra-style %}

<style>
    body {
        text-align: center;
        background-color: #ddd;
    }
    .inputBox {
        margin: auto;
        width: 70%;
        background: white;
        height: 50px;
        border-radius: 50px;
        line-height: 50px;
    }
    .inputBox .name {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 70px;
        padding-left: 20px;
    }
    .inputBox .item {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 400px;
        margin-left: 50px;
        padding-left: 20px;
    }
    .todoList {
        list-style: none;
        padding: 10px 0;
        text-align: left;
    }
    .todoList li {
        display: flex;
        height: 50px;
        line-height: 50px;
        margin: 0.5rem 0;
        padding: 0 0.9rem;
        background: white;
        border-radius: 5px;
    }
    .removeBtn {
        margin-left: auto;
        font-size: 20px;
        cursor: pointer;
    }
</style>
{% endblock extra-style %} {% block content %}
<div id="app">
    <h1>To Do Delete</h1>
    <p>Are you sure to delete {{object}}?</p>
    <br />

    <form action="." method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-sm">Confirm</button>
    </form>
</div>
{% endblock content %}

only_used_one_of_vue_and_django/Django/to_do/templates/todo/todo_form.html
{% extends "base.html" %} {% block title %}Vue-Django ToDo App{% endblock %} {% block extra-style %}

<style>
    body {
        text-align: center;
        background-color: #ddd;
    }
    .inputBox {
        margin: auto;
        width: 70%;
        background: white;
        height: 50px;
        border-radius: 50px;
        line-height: 50px;
    }
    .inputBox .name {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 90px;
        padding-left: 20px;
        line-height: 20px;
    }
    .inputBox .item {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 400px;
        margin-left: 50px;
        padding-left: 20px;
        line-height: 20px;
    }
    .todoList {
        list-style: none;
        padding: 10px 0;
        text-align: left;
    }
    .todoList li {
        display: flex;
        height: 50px;
        line-height: 50px;
        margin: 0.5rem 0;
        padding: 0 0.9rem;
        background: white;
        border-radius: 5px;
    }
    .removeBtn {
        margin-left: auto;
        font-size: 20px;
        cursor: pointer;
    }
</style>
{% endblock %} {% block content %}
<div>
    <h1>My To Do App !</h1>
    <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
    <br />

    <form class="inputBox" action="." method="post">
        {% csrf_token %}
        <input class="name" type="text" placeholder="name ..." name="name" />
        <input class="item" type="text" placeholder="type anything welcomed ..." name="todo" />
        <button class="btn btn-info btn-sm" type="submit">ADD</button>
    </form>
</div>
{% endblock %}

only_used_one_of_vue_and_django/Django/to_do/templates/todo/todo_form_list.html
{% extends "base.html" %} {% block title %}Vue-Django ToDo App{% endblock %} {% block extra-style %}

<style>
    body {
        text-align: center;
        background-color: #ddd;
    }
    .inputBox {
        margin: auto;
        width: 70%;
        background: white;
        height: 50px;
        border-radius: 50px;
        line-height: 50px;
    }
    .inputBox .name {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 90px;
        padding-left: 20px;
        line-height: 20px;
    }
    .inputBox .item {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 400px;
        margin-left: 50px;
        padding-left: 20px;
        line-height: 20px;
    }
    .todoList {
        list-style: none;
        padding: 10px 0;
        text-align: left;
    }
    .todoList li {
        display: flex;
        height: 50px;
        line-height: 50px;
        margin: 0.5rem 0;
        padding: 0 0.9rem;
        background: white;
        border-radius: 5px;
    }
    .removeBtn {
        margin-left: auto;
        font-size: 20px;
        cursor: pointer;
    }
</style>
{% endblock %} {% block content %}
<div>
    <h1>My To Do App !</h1>
    <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
    <br />

    <form class="inputBox" action="." method="post">
        {% csrf_token %}
        <input class="name" type="text" placeholder="name ..." name="name" />
        <input class="item" type="text" placeholder="type anything welcomed ..." name="todo" />
        <button class="btn btn-info btn-sm" type="submit">ADD</button>
    </form>

    <ul class="todoList">
        {% for todo in object_list %}
        <li>
            <span>{{ todo.name }}: {{ todo.todo }}</span>
            {% comment %}
            <button
                type="button"
                class="removeBtn"
                data-bs-toggle="modal"
                data-bs-target="#myModal"
                data-bs-id="{{todo.id}}"
                data-bs-name="{{todo.name}}"
                data-bs-todo="{{todo.todo}}"
            >
                &#x00D7;
            </button>
            {% endcomment %}

            <button
                type="button"
                class="removeBtn btn btn-sm"
                data-bs-toggle="modal"
                data-bs-target="#myModal"
                data-bs-id="{{todo.id}}"
                data-bs-name="{{todo.name}}"
                data-bs-todo="{{todo.todo}}"
            >
                &#x00D7;
            </button>
        </li>
        {% endfor %}
    </ul>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fs-5" id="myModalLabel">Are you sure to delete ?</h5>
                </div>
                <div class="modal-body">body-text</div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger btn-sm">
                        <a href="">Delete</a>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block extra-script %}
<script>
    const myModal = document.getElementById('myModal');
    if (myModal) {
        myModal.addEventListener('show.bs.modal', (event) => {
            console.log('hi');
            const button = event.relatedTarget;
            const id = button.getAttribute('data-bs-id');
            const name = button.getAttribute('data-bs-name');
            const todo = button.getAttribute('data-bs-todo');

            const modalBody = myModal.querySelector('.modal-body');
            const modalFooter = myModal.querySelector('.modal-footer a');

            modalBody.textContent = name + ':' + todo;
            modalFooter.setAttribute('href', '/todo/' + id + '/delete2/');
        });
    }
</script>
{% endblock %}

only_used_one_of_vue_and_django/Django/to_do/templates/todo/todo_list.html
{% extends "base.html" %} {% block title %}todo_list.html{% endblock title %} {% block extra-style %}

<style>
    body {
        text-align: center;
        background-color: #ddd;
    }
    .inputBox {
        margin: auto;
        width: 70%;
        background: white;
        height: 50px;
        border-radius: 50px;
        line-height: 50px;
    }
    .inputBox .name {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 70px;
        padding-left: 20px;
    }
    .inputBox .item {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 400px;
        margin-left: 50px;
        padding-left: 20px;
    }
    .todoList {
        list-style: none;
        padding: 10px 0;
        text-align: left;
    }
    .todoList li {
        display: flex;
        height: 50px;
        line-height: 50px;
        margin: 0.5rem 0;
        padding: 0 0.9rem;
        background: white;
        border-radius: 5px;
    }
    .removeBtn {
        margin-left: auto;
        font-size: 20px;
        cursor: pointer;
    }
    .addBtn {
        cursor: pointer;
    }
</style>
{% endblock extra-style %} {% block content %}

<div>
    <h1>My To Do App !</h1>
    <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
    <br />

    <ul class="todoList">
        {% for todo in object_list %}
        <li>
            <span>{{ todo.name }}: {{ todo.todo }}</span>
            <span class="removeBtn">
                <a href="{% url 'todo:delete' todo.id %}">&#x00D7;</a>
            </span>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

only_used_one_of_vue_and_django/Django/to_do/templates/todo/todo_vue_only.html
{% extends "base.html" %} {% block title %}todo_vue_only.html{% endblock title %} {% block extra-style %}

<style>
    body {
        text-align: center;
        background-color: #ddd;
    }
    .inputBox {
        margin: auto;
        width: 70%;
        background: white;
        height: 50px;
        border-radius: 50px;
        line-height: 50px;
    }
    .inputBox .name {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 90px;
        padding-left: 20px;
        line-height: 20px;
    }
    .inputBox .item {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 400px;
        margin-left: 50px;
        padding-left: 20px;
        line-height: 20px;
    }
    .todoList {
        list-style: none;
        padding: 10px 0;
        text-align: left;
    }
    .todoList li {
        display: flex;
        height: 50px;
        line-height: 50px;
        margin: 0.5rem 0;
        padding: 0 0.9rem;
        background: white;
        border-radius: 5px;
    }
    .removeBtn {
        margin-left: auto;
        font-size: 20px;
        cursor: pointer;
    }
    .addBtn {
        cursor: pointer;
    }
</style>
{% endblock extra-style %} {% block content %}

<div id="app">
    <h1>My To Do App !</h1>
    <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
    <br />

    <div class="inputBox">
        <input v-model="name" class="name" type="text" placeholder="name ..." />
        <input v-model="newToDoItem" class="item" type="text" placeholder="type anything welcomed ..." v-on:keyup.enter="addToDo()" />
        <button v-on:click="addToDo()" class="btn btn-primary btn-sm">ADD</button>
    </div>

    <ul class="todoList">
        <li v-for="(toDo, index) in toDoItems">
            <span>{ toDo.name }: { toDo.item }</span>
            <span class="removeBtn" v-on:click="removeToDo(index)">&#x00D7;</span>
        </li>
    </ul>
</div>
{% endblock content %} {% block extra-script %}
<script src="https://unpkg.com/vue@2"></script>
<script>
    var vm = new Vue({
        delimiters: ['{', '}'],
        el: '#app',
        data: {
            name: '',
            newToDoItem: '',
            toDoItems: [
                { name: '김유현', item: 'Django 와 Vue.js 연동 프로그램을 만들고 있습니다.' },
                { name: '홍길동', item: '이름을 안쓰면 홍길동으로 나와요...' },
                { name: '이순신', item: '신에게는 아직 열두 척의 배가 있사옵니다.' },
                { name: '성춘향', item: '그네 타기' },
            ],
        },
        methods: {
            addToDo: function () {
                if (this.name == '') this.name = '김유현';
                if (this.newToDoItem == '') {
                    this.name = '';
                    return;
                }
                this.toDoItems.push({ name: this.name, item: this.newToDoItem });
                this.name = '';
                this.newToDoItem = '';
            },
            removeToDo: function (index) {
                this.toDoItems.splice(index, 1);
            },
        },
    });
</script>
{% endblock extra-script %}